spring:
  h2:
    console:
      #Essa configuração permite você acessar o banco via navegador
      #http://localhost:8080/h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
