  projet:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@

  info:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@


  ---

  #Configuração do TOMCAT
#  server:
#    servlet:
#      context-path: /
#    port: 8080
#    tomcat:
#      max-wait: 20000
#      ma