projet:
    name: ${project.artifactId}
    version: ${project.version}
    description: ${projeto.description}

info:
    build:
        artifact: @project.artifactId@
        name: @project.name@
        description: @project.description@
        version: @project.version@

---

#Configuração do TOMCAT
server:
    servlet:
        context-path: /
    port: 8080
    tomcat:
        max-wait: 20000
        max-active: 50
        max-idle: 20
        main-idle: 15

spring:
    output:
        ansi:
            enabled: always


controller:
    user-get: Método responsável para exibir dos dados do usuário.
    post-get: Método responsável para exibir dos dados do post.
    comments-get: Método responsável para exibir dos dados do comments.

